version: '3' # Version of the Docker Compose file format
name: elemental-zcash-sso
services:
  api:
    environment:
      - VIRTUAL_HOST=api.elemental-sso.local
      - VIRTUAL_PORT=8080
    # labels:
    #   - dev.orbstack.domains=api.elemental-sso.local
  sso_web:
    build:
      context: ./packages/web
      target: dev
    command: npm run dev
    environment:
      - VIRTUAL_HOST=elemental-sso.local
      - VIRTUAL_PORT=3000
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_ENV=local
    volumes:
      - ./packages/web:/app
      - /app/node_modules
      - /app/.next
    # labels:
    #   - dev.orbstack.domains=elemental-sso.local


  # web:
  #   environment:
  #     - VIRTUAL_HOST=elemental-sso.local
  #     - VIRTUAL_PORT=3000
  #     - NODE_ENV=development
