version: '3'
services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      - "REDIS_ARGS=--requirepass ${REDIS_PSWD}"
    networks:
      - elemental_net
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.1-alpine
    container_name: sso-nginx-proxy
    #volumes:
    #  - ./vhost.d:/etc/nginx/vhost.d:ro
    # build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    #environment:
    #  - DEFAULT_HOST=error.local
    networks:
      - elemental_net
    depends_on:
      - redis
  api:
    build: ./packages/api
    environment:
      - PORT=8081
    networks:
      - sso_net
      - elemental_net
    env_file:
      ./packages/api/.env
    #volumes:
    #  - ./packages/api:/usr/src/app
    links:
      - redis
      # - database
    depends_on:
      - nginx-proxy
      - redis
networks:
  sso_net:
  elemental_net:
    external: true
    driver: bridge
