version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.1-alpine
    container_name: sso-nginx-proxy
    # volumes:
    #  - ./nginx/nginx.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    # build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    #environment:
    #  - DEFAULT_HOST=error.local
    networks:
      - elemental_net
      - sso_next_net
  # mail_check:
  #   image: reacherhq/backend:latest
  #   container_name: mail_check
  #   hostname: mail_check
  #   ports:
  #     - "8089:8089"
  #   environment:
  #     - PORT=8089
  #     - RCH_HTTP_HOST=0.0.0.0
  #   networks:
  #     - elemental_net
  #     - sso_net
  api:
    build: ./packages/api
    environment:
      - PORT=8081
    networks:
      - sso_net
      # - sso_next_net
      - elemental_net
    env_file:
      ./packages/api/.env
    #volumes:
    #  - ./packages/api:/usr/src/app
    # links:
    #   - redis
      # - zecwallet_api
      # - database
    depends_on:
      - nginx-proxy
networks:
  sso_net:
  sso_next_net:
    # external: true
    driver: bridge
  elemental_net:
    external: true
    driver: bridge
