version: '3' # Version of the Docker Compose file format
services:
  sso_web:
    environment:
      - VIRTUAL_HOST=sso-staging.elementalzcash.com
      - VIRTUAL_PORT=3000
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_ENV=staging
