version: '3'
services:
  sso_web:
    build: ./
    environment:
      - PORT=3000
    networks:
      - sso_net
      - elemental_net
      # - elemental_net
    # depends_on:
    #   - nginx-proxy
networks:
  sso_net:
  elemental_net:
    external: true
    driver: bridge
  # elemental_net:
  #   external: true
  #   driver: bridge
