version: '3'
services:
  api:
    build: .
    environment:
      - PORT=8081
    networks:
      - elemental_net
    env_file:
      .env
networks:
  elemental_net:
    external: true
    driver: bridge
