"""empty message

Revision ID: 49fdbfb5cc3f
Revises: 4a525b47a0b1
Create Date: 2023-03-18 19:34:57.556015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fdbfb5cc3f'
down_revision = '4a525b47a0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('unverified_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('zcashaddress', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('unverified_zcashaddress', sa.Text(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_users_unverified_email'), ['unverified_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)
        batch_op.drop_column('public_zcashaddress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_zcashaddress', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_unverified_email'))
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('unverified_zcashaddress')
        batch_op.drop_column('zcashaddress')
        batch_op.drop_column('unverified_email')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
