version: '3'
services:
  sso_flask_server:
    build: ./
    ports:
      - "3535:5000"
    hostname: sso_flask_server
    env_file:
    - .env
    container_name: sso_flask_server
    networks:
      - elemental_net
networks:
  elemental_net:
    external: true
    driver: bridge
