# name: Deploy to Environment

# on:
#   push:
#     branches:
#       - main
#       - staging
#       - 'release/*'
#     pull_request:
#       types: [opened, synchronize]


# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     # - name: Checkout code
#     #   uses: actions/checkout@v2
#     - name: Deploy to staging
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SERVER_HOST }}
#         username: ${{ secrets.SERVER_USERNAME }}
#         key: ${{ secrets.SERVER_KEY }}
#         port: ${{ secrets.SERVER_SSH_PORT }}
#         script: update sso main
